# -*- coding: utf-8 -*-
"""Final_fmlcode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HxQmp_hZkqbwJ7DymqvWPPRhJnHQGUsI
"""

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score,precision_score,recall_score

newstrain = pd.read_csv("train.csv")

"""Ytest.head()"""

newstrain=newstrain.fillna('')
newstrain['title']=newstrain['title'].str.lower()
newstrain['author']=newstrain['author'].str.lower()
newstrain['text']=newstrain['text'].str.lower()

newstrain.drop(columns='id',axis=0)

newstrain['monk']=newstrain['author']+' '+newstrain['title']+' '+newstrain['text']

X = newstrain['monk'].values   
Y = newstrain['label'].values

# X and X_test are vectorized data 
# Y and Y_test are values only

vectorizer = TfidfVectorizer()
vectorizer.fit(X)

X = vectorizer.transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.8, random_state=2)

logistic=linear_model.LogisticRegression()
logistic.fit(X_train,Y_train)

Y_predicted=logistic.predict(X_train)
train_accuracy = accuracy_score(Y_predicted,Y_train)

print(train_accuracy)


Y_test_predicted=logistic.predict(X_test)
test_accuracy = accuracy_score(Y_test_predicted,Y_test)

print(test_accuracy)

score=f1_score(Y_train, Y_predicted)
print(score)

classify = logistic.predict(X_test[3])

if classify==0:
  print("This news is Real")
else:
  print("This news is Fake")

score=f1_score(Y_train, Y_predicted)
test_accuracy = accuracy_score(Y_test_predicted,Y_test)
recall=recall_score(Y_test, Y_test_predicted)
precision=precision_score(Y_test, Y_test_predicted)
print(f'Accuracy: {round(test_accuracy * 100, 2)}%')
print(f'F1 Score: {round(score * 100, 2)}%')
print(f'Recall: {round(recall * 100, 2)}%')
print(f'Precision: {round(precision * 100, 2)}%')
